name: "infra preview & deploy"

on:
  push:
    - main
    paths:
      - 10_infa/**
      - .github/workflows/**

  workflow_dispatch:

Permissions:
  id-token: write
  contents: read

jobs:
  preview:
    name: "Preview"
    runs-on: ubuntu-latest
    steps:
      - run echo "Hello world"


